---
title: "example"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{example}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# 1) Library
```{r setup}
library(StochOptim)
```


# 2) Function Definition
```{r}
fn <- rastrigin <- function(x) {
  y <- ( 10 * length(x) + sum(x^2 - 10 * cos(2 * pi * x)))
  return(y)
}

D <- 10
lower <- lb <- rep(-5.2, D)
upper <- ub <- rep(5.2, D)
par <- rep(3.3, D)
```

# 3) DEoptim
```{r}
# DEoptim --------------------------------------

ctrl1 <- list(popsizee = 10*length(lb),
              maxiterr = 200*length(lb),
              tol  = 1e-10,
              trace   = 4)

set.seed(123)
final_ans <- global_wrapper(fn     = rastrigin,
                           lower   = lb,
                           upper   = ub,
                           method  = "DEoptim",
                           control = ctrl1)
```

# 4) PSO
```{r}
## pso ---------------------------------------

# PSO
## Rastrigin function - local refinement with L-BFGS-B on improvements

ctrl2 <- list(tol = 1e-8, hybrid = "improved", trace = 0)

final_ans2 <- global_wrapper(par     = rep(1,D),
                            fn      = rastrigin,
                            lower   = lb,
                            upper   = ub,
                            method  = "pso",
                            control = ctrl2)
```

# 5) GenSA
```{r}
## GenSA ------------------------------------

# GenSA will stop after finding the targeted function value 0 with
# absolute tolerance 1e-13

global_min <- 0
tol <- 1e-13
ctrl3 <- list(threshold.stop = global_min + tol, trace = 3)

final_ans3 <- global_wrapper(fn      = rastrigin,
                            lower   = lb,
                            upper   = ub,
                            method  = "GenSA",
                            control = ctrl3)

# note GenSA returns almost similar output as printed by GlobalWrapper
#final_ans3
```

# 6) DEoptimR

```{r}
griewank <- function(x) {
  1 + crossprod(x)/4000 - prod( cos(x/sqrt(seq_along(x))) )
}

ctrl4 <- list(tol = 1e-7, trace = 5)
final_ans4 <- global_wrapper(fn      = griewank,
                             lower   = rep(-600, 10),
                             upper   = rep(600, 10),
                             method  = "DEoptimR",
                             control = ctrl4)
```

# 7) adagio

```{r}
ctrl5 <- list(popsize  = 70, 
              nmax     = 230,
              r        = 0.41, 
              confined = TRUE, 
              trace    = 0)

final_ans5 <- global_wrapper(
               fn = rastrigin, 
               lower = lb, 
               upper = ub, 
               method = "adagio_simpleDE", 
               control = ctrl5)
```
