---
title: "sopm"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{sopm}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(stochoptim)
```

```{r}
fn <- rastrigin <- function(x) {
  y <- ( 10 * length(x) + sum(x^2 - 10 * cos(2 * pi * x)))
  return(y)
}

D <- 10
lower <- lb <- rep(-5.2, D)
upper <- ub <- rep(5.2, D)
par <- rep(3.3, D)
```

```{r}
DEoptim = list(
  popsize = 10*length(lb),
  maxiter = 200*length(lb),
  tol  = 1e-10,
  trace   = FALSE)

GenSA  = list(maxiter = 100)
pso    = list(abstol= 1e-8, hybrid = "improved")
DEoptimR = list(tol = 1e-7, trace = FALSE)
adagio_simpleDE = list(
  popsize  = 70, 
  nmax     = 230,
  r        = 0.41, 
  confined = TRUE, 
  trace    = FALSE)

 control <- list(DEoptim, GenSA, pso, DEoptimR, adagio_simpleDE)

sopm(par = par, 
     fn = fn,
     lower = lb, 
     upper = ub, 
     method = c("DEoptim", "GenSA","pso","DEoptimR","adagio_simpleDE"),
     control= control)
```
## Common parameter in control list

Some of the optimizers share common control list parameter like `maxiter` so it need not be passed separately in each control list. (For now there is only one such parameter but adding new things is just a matter of adding parameter in a list.)

```{r}
# popsize and maxiter are common parameter for DEoptim and GenSA

control <- list(maxiter = 100,
  DEoptim = list(tol = 1e-10), GenSA = list(maxiter = 100))

sopm(par = par, fn = fn,lower = lb, upper = ub, method = c("DEoptim","GenSA") ,control = control)
```


